using System.Collections.Generic;

namespace SoundEventEditor.Localisation
{
    public static class English
    {
        public static readonly Dictionary<string, string> MainStrings = new()
        {
            { "Name", "Name" },
            { "MaxVoices", "Max Voices" },
            { "MaxVoicesBehaviour", "Max Voices Behaviour" },
            { "Default", "Default" },
            { "Replace", "Replace" },
            { "Global", "Global" },
            { "MainFiletype", "Main Filetype" },
            { "FiletypeGen7", "Filetype (Gen 7)" },
            { "NoOcclusion", "No Occlusion" },
            { "MixUpdate", "Mix Update" },
            { "NoRear", "No Rear" },
            { "ForceNonPos", "Force Non Pos" },
            { "OverrideUserMusic", "Override User Music" },
            { "ShouldLoopFlag", "Should Loop" },
            { "FallOffTypeInverse", "Fall Off Type Inverse" },
            { "Regional", "Regional" },
            { "LoadPriority", "Load Priority" },
            { "FieldAngleMin", "Field Angle Min" },
            { "FieldAngleMax", "Field Angle Max" },
            { "BleedAngle", "Bleed Angle" },
            { "BleedNear", "Bleed Near" },
            { "BleedFar", "Bleed Far" },
            { "LowPassNear", "Low Pass Near" },
            { "LowPassFar", "Low Pass Far" },
            { "FadeIn", "Fade In" },
            { "FadeOut", "Fade Out" },
            { "PitchRampUpTime", "Pitch Ramp Up Time" },
            { "PitchRampDownTime", "Pitch Ramp Down Time" },
            { "Near", "Near" },
            { "Far", "Far" },
            { "Volume", "Volume" },
            { "RandomVolume", "Random Volume" },
            { "Pitch", "Pitch" },
            { "RandomPitch", "Random Pitch" },
            { "PitchTimeScaleFactor", "Pitch Time Scale Factor" },
            { "LowPass", "Low Pass" },
            { "RandomLowPass", "Random Low Pass" },
            { "LowPassQ", "Low Pass Q" },
            { "LFEMix", "LFE Mix" },
            { "ReverbWetMix", "Reverb Wet Mix" },
            { "StartOffset", "Start Offset" },
            { "RandomStartOffset", "Random Start Offset" },
            { "DopplerEffectScalar", "Doppler Effect Scalar" },
            { "LoopFactor", "Loop" },
            { "StartPitch", "Start Pitch" },
            { "TargetPitch", "Target Pitch" },
            { "EndPitch", "End Pitch" },
            { "Filename", "Filename" },
            { "Mix", "Mix" },
            { "RoutingTable", "Routing Table" },
            { "Cues", "Cues" },
            { "Behaviour", "Behaviour" },
            { "RetryOnFailure", "Retry On Failure" },
            { "DuckScale", "Duck Scale" },
            { "SubAlwaysOn", "Sub Always On" },
            { "Delay", "Delay" },
            { "OnFailedInterruptWait", "On Failed Interrupt Wait" },
            { "PlayPriority", "Play Priority" },
            { "PriorityOverSame", "Priority Over Same" },
            { "HighPriority", "High Priority" },
            { "Characters", "Characters" },
            { "Buses", "Buses" },
            { "VAG", "VAG" },
            { "OGG", "OGG" },
            { "UNK3", "Unknown Filetype 3" },
            { "CBX", "CBX" },
            { "SampleSettings", "Sample Settings" },
            { "FileSettings", "File Settings" },
            { "OutputSettings", "Output Settings" },
            { "CharacterName", "Character Name" },
            { "NoFlappy", "No Flappy" },
            { "FacialAnimationSet", "Facial Animation Set" },
            { "FacialAnimationAction", "Facial Animation Action" },
            { "BodyAnimationSet", "Body Animation Set" },
            { "BodyAnimationAction", "Body Animation Action" },
        };
    }
}
